# Generated by Django 4.1.7 on 2023-02-28 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cat',
            new_name='Vinyl',
        ),
    ]
