# Generated by Django 4.1.7 on 2023-03-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_cat_vinyl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sound', models.CharField(choices=[('E', 'Epic'), ('C', 'Copacetic'), ('D', 'Defective')], default='E', max_length=1)),
            ],
        ),
    ]
